### ISSUE TITLE
SIGSEGV on cargo test on Mac OS

### ISSUE THREAD

**Issue by mantono** [mantono/fwalker#12]
**Describe the bug**
[Unable to run tests (Mac OS only)](https://github.com/mantono/fwalker/runs/1674034895?check_suite_focus=true). Running `cargo test` results in
> (signal: 11, SIGSEGV: invalid memory reference)

**Stacktrace**
No backtrace availlable on SIGSEV

**Context**
Please include
- Operating system: Mac OS: Darwin Mac-1610214732616.local 19.6.0 
- OS/kernel version: Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
- Version of rustc: rustc 1.49.0 (e1884a8e3 2020-12-29)

**Debugging**
Github worklflow runner can be accessed via a SSH session for additional debugging. Error has been reproduced on the runner host both with stable and nightly channel.

The following will have to be executed in order to have a working rust environment on the workflow runner;
> export CARGO_HOME="/Users/runner/.cargo"
> export PATH=/Users/runner/.cargo/bin:$PATH
> rustup toolchain install stable

Project source code is found in
> cd /Users/runner/work/fwalker/fwalker

The issue is probably with [rust](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+%28signal%3A+11%2C+SIGSEGV%3A+invalid+memory+reference) or [cargo](https://github.com/rust-lang/cargo/issues?q=is%3Aissue+%28signal%3A+11%2C+SIGSEGV%3A+invalid+memory+reference+). Will have to test with never versions when they are released.

**Comment by williamhogman** [comment]
Can confirm this issue

```
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/william.rudenmalmhogman/code/w/fwalker/target/debug/deps/fwalker-76b066772f2f1f02` (signal: 11, SIGSEGV: invalid memory reference)
```
